// This file is auto-generated by fetch_data.py
// Data embedded as TypeScript module for serverless compatibility
export const marketData = {
  "updated_at": "2026-04-02 16:18",
  "indices": {
    "sh000001": { "name": "上证指数", "price": "3940.80", "pct": "-0.20", "high": "3952.58", "low": "3900.12" },
    "sz399001": { "name": "深证成指", "price": "13658.25", "pct": "-0.35", "high": "13680.63", "low": "13418.50" },
    "sz399006": { "name": "创业板指", "price": "3229.60", "pct": "-0.55", "high": "3229.68", "low": "3155.13" },
    "sh000300": { "name": "沪深300", "price": "4514.44", "pct": "-0.26", "high": "4519.69", "low": "4459.61" }
  },
  "limit_up": [
    {"symbol":"bj920230","code":"920230","name":"欧康医药","trade":"14.610","pricechange":3.37,"changepercent":29.982,"volume":11857463,"amount":166292836},
    {"symbol":"sz300834","code":"300834","name":"星辉环材","trade":"43.490","pricechange":7.25,"changepercent":20.006,"volume":22421575,"amount":939894278},
    {"symbol":"sz300839","code":"300839","name":"博汇股份","trade":"16.690","pricechange":2.78,"changepercent":19.986,"volume":18945600,"amount":316234560}
  ],
  "limit_down": [],
  "stocks": []
};
